controlo_financeiro/urls.py
from django.views.static import serve,static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from financial_control.views import homepage_view

urlpatterns = [
    path('tipodespesa/', include('financial_control.url_tipodespesa')),
    path('despesa/', include('financial_control.url_despesa')),
    #path('receita/', include('financial_control.url_receita')),
    path('', homepage_view, name='homepage-view'),
    path('home/', homepage_view, name='homepage-view'),
    path('admin/', admin.site.urls),
    path('accounts/', include('financial_control.url_accounts')),
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

financial_control/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone
from django.utils.timezone import now
from django.urls import reverse
from django import template
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime


# Create your models here.
class TipoDespesa(models.Model):
    nome = models.CharField(max_length=50,blank=False, null=True)
    descricao = models.TextField(max_length=150,blank=False, null=True)
    date = models.DateTimeField(auto_now_add=True, blank=False, null=True)
    user = models.IntegerField(blank=True, null=True) # Blank Significa que nao precisamos de introduzir valor manualmente!

    def __str__(self):
        return self.nome

    def get_detalhes_url(self):
        return reverse("tipodespesa-detalhes-view", kwargs={"my_id": self.id})

    def get_atualiza_url(self):
        return reverse("tipodespesa-atualiza-view", kwargs={"my_id": self.id})

    def get_elimina_url(self):
        return reverse("tipodespesa-elimina-view", kwargs={"my_id": self.id})

    def get_total_despesas_url(self):
        return reverse("tipodespesa-total-despesas-view", kwargs={"my_id": self.id})


class Despesa(models.Model):
    nome = models.CharField(max_length=50,blank=True, null=True)
    descricao = models.CharField(max_length=150,blank=True, null=True)
    valor = models.DecimalField(max_digits=7, decimal_places=2, blank=False, null=True)
    date = models.DateTimeField(blank=False, null=True)
    user = models.IntegerField(blank=True, null=True)
    tipo_despesa = models.ForeignKey(TipoDespesa, on_delete=models.SET_NULL, null=True)
    # on_delte=models.SET_NULL permite que possamos eliminar um tipo de despesa, sem as despesas serem eliminadas tmb em cascada, mas mesmo assim nao podemos deixar eliminar um tipo de despesa se tiver despesas associadas!

    def __str__(self):
        return self.nome

    def get_detalhes_url(self):
        return reverse("despesa-detalhes-view", kwargs={"my_id": self.id})

    def get_atualiza_url(self):
        return reverse("despesa-atualiza-view", kwargs={"my_id": self.id})

    def get_elimina_url(self):
        return reverse("despesa-elimina-view", kwargs={"my_id": self.id})


class Receita(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    descricao = models.CharField(max_length=300, blank=True, null=True)
    valor = models.FloatField(validators=[MaxValueValidator(1000000), MinValueValidator(0)], blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, blank=False, null=True)
    user = models.IntegerField(blank=False, null=False)

    def __str__(self):
        return self.nome

financial_control/forms.py
#The forms.py is where we should add the extra validations that we want to apply to the input forms income data/info
from django import forms
from django.core.exceptions import ValidationError
import datetime
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Despesa, TipoDespesa, Receita


class TipoDespesaRegistoForm(forms.ModelForm):
    nome = forms.CharField(label=False, required=True)
    descricao = forms.CharField(label=False, widget=forms.Textarea(attrs={'name':'body', 'rows':3, 'cols':23}), required=True)
    user = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = TipoDespesa
        fields = [
            'nome',
            'descricao',
            'user'
        ]

    def clean_date(self):
        date = self.cleaned_data['date']
        if date > datetime.date.today():
            raise forms.ValidationError("The date must be the current day or before!")
        return date


class DespesaRegistoForm(forms.ModelForm):
    # Has to be forms.ModelForm, otherwise we cant use form.save() in the view
    nome = forms.CharField(label=False, required=True)
    descricao = forms.CharField(label=False, widget=forms.Textarea(attrs={'name':'body', 'rows':3, 'cols':23}), required=False)
    valor = forms.DecimalField(label=False, widget=forms.TextInput(attrs={"placeholder": "Formato: 2.00"}))
    user = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    tipo_despesa = forms.ModelChoiceField(queryset=TipoDespesa.objects.all(), label=False, required=True)
    date = forms.DateField(initial=datetime.date.today(), label=False, required=True)


    class Meta:
        model = Despesa
        fields = [
            'nome',
            'descricao',
            'valor',
            'user',
            'tipo_despesa',
            'date'
        ]

    def clean_date(self):
        date = self.cleaned_data['date']
        if date > datetime.date.today():
            raise forms.ValidationError("The date must be the current day or before!")
        return date


class ReceitaForm(forms.ModelForm):
    nome = forms.CharField(label=False, widget=forms.TextInput(attrs={"placeholder": "Name"}), required=True)
    descricao = forms.CharField(label=False, widget=forms.TextInput(attrs={"placeholder": "Description"}), required=True)

    class Meta:
        model = Receita
        fields = [
            'nome',
            'descricao'
        ]


class LoginForm(forms.Form):
    username = forms.CharField(label=False, widget=forms.TextInput(attrs={"placeholder": "Username"}), required=True)
    password = forms.CharField(label=False, widget=forms.PasswordInput(attrs={"placeholder": "Password"}), required=True)

financial_control/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.contrib.auth.models import User

# Create your views here.
def homepage_view(request):
    return render(request, "home.html")


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        username = form.data.get("username")
        password = form.data.get("password")

        user = authenticate(request, username=username, password=password)
        #If the user is authenticated and valid
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('homepage-view'))
        else:
            messages.info(request, 'Invalid Credentials')
            return HttpResponseRedirect(reverse('login'))
    else:
        return render(request, 'accounts/login.html', {"form": form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('homepage-view'))

financial_control/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<style>
    .login-form {
        width: 340px;
        margin: 50px auto;
        font-size: 15px;
    }
    .login-form form {
        margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .btn {
        font-size: 15px;
        font-weight: bold;
    }
</style>
<div class="login-form">
    <form method="POST">
        {% csrf_token %}
        <h2 class="text-center">Log in</h2>
        <div class="form-group">
            <label for="username" class="col-md-4 control-label text-right">Username:</label>
            <div class="col-md-6">
                {{ form.username}}
            </div>
        </div>
        <div class="form-group">
             <label for="password" class="col-md-4 control-label text-right">Password:</label>
            <div class="col-md-6">
                {{ form.password}}
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
    </form>
    <div>
        {% for message in messages %}
            <div class="alert alert-warning border border-dark" role="alert">
              <h3> {{ message }}</h3>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

financial_control/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  <!-- CSS for NavBar design mainly -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> <!-- BootStrap CSS 1-->
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}"><!-- Tables CSS -->
    <link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}"><!-- Tables CSS -->
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}"> <!-- DataTable Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}"><!-- DataPicker CSS -->
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">

    <!-- Needed Scripts  -->
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script> <!-- Jquery 3.5.1 -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script><!-- DataTable Script -->
    <script src="{% static 'js/dataTables.buttons.min.js' %}"></script><!-- DataTabel Export Buttons-->
    <script src="{% static 'js/buttons.html5.min.js' %}"></script> <!-- DataTabel Export Buttons Appear-->
    <script src="{% static 'js/pdfmake.min.js' %}"></script><!-- DataTabel Export PDF -->
    <script src="{% static 'js/vfs_fonts.js' %}"></script><!-- DataTabel Export PDF needed to Pdf export work -->
    <script src="{% static 'js/jquery-ui.js' %}"></script><!-- DataPicker Script -->
    <script src="{% static 'js/chart.min.js' %}"></script> <!-- Charts.js -->
    <script src="{% static 'js/adminlte.min.js' %}"></script>

    <title>Controlo Financeiro</title>
  </head>
  <body>
    <!-- NavBar/Menu -->
    <div class="bg-light sticky-top">
        {% include 'navbar.html'  %}
    </div>

    <!-- Page Body/Content -->
    <div class="container pt-4">
         {% block content %}
         Replace me Block
         {% endblock %}
    </div>
  </body>

  <!-- Popper.js, then Bootstrap JS -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

financial_control/templates/despesa/despesa_atualiza.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container w-75 p-3 rounded bg-light border border-dark">
    <h1>Atualizar Despesa - <span style="color:blue;">{{ despesa.nome}}</span> </h1>
    <p>Nesta área pode editar/atualizar as informações acerca da despesa.</p><br>
    <form method="POST">
      {% csrf_token %}
      <div class="row mb-3">
        <label class="col col-form-label">Name</label>
        <div class="col-sm-10">
          {{ form.nome}}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Description</label>
        <div class="col-sm-10">
          {{ form.descricao}}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Valor ( € )</label>
        <div class="col-sm-10">
          {{ form.valor|as_crispy_field }}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Tipo</label>
        <div class="col-sm-10">
          {{ form.tipo_despesa}}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>
{% endblock %}

financial_control/templates/despesa/despesa_detalhes.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h1>Despesa- Detalhes</h1><br>
        <div class="card card-primary text-dark border border-dark mb-3" style="max-width:40rem;">
          <div class="card-header"><h4>{{ despesa.nome }}</h4></div>
          <div class="card-body">
            <p class="card-text"><b>ID:</b> {{ despesa.id }}</p>
            <p class="card-text"><b>Nome:</b> {{ despesa.nome }}</p>
            <p class="card-text"><b>Descricão:</b> {{ despesa.descricao }}</p>
            <p class="card-text"><b>Tipo:</b> {{ despesa.tipo_despesa }}</p>
            <p class="card-text"><b>Valor ( € ) :</b> {{ despesa.valor }}</p>
            <p class="card-text"><b>Data de Criacao:</b> {{ despesa.date }}</p>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{{ despesa.get_atualiza_url }}" class="btn btn-secondary">Editar</a>
                <a href="{{ despesa.get_elimina_url }}" class="btn btn-danger">Eliminar</a>
            </div>
          </div>
        </div>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More Options..
          </button>
          <div class="dropdown-menu bg-primary">
            <a class="dropdown-item bg-primary text-light" href="">teste1</a>
            <a class="dropdown-item bg-primary text-light" href="">teste2</a>
          </div>
        </div>
    </div>
</div>
{% endblock %}

financial_control/templates/despesa/despesa_elimina.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="card card-danger text-dark border border-dark bg-light mb-3" style="max-width:40rem;">
          <div class="card-header"><h3>{{ despesa.nome }}</h3></div>
          <div class="card-body">
                <form action='.' method="POST"> {% csrf_token %}

      <h3>Tem a certeza que pretende eliminar definitivamente esta despesa?</h3><br>
      <p><input type='submit' value='Sim' />&nbsp;&nbsp;<a href="{% url 'despesa-lista-view' %}">Cancelar</a></p>

  </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}>

financial_control/templates/despesa/despesa_lista.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block content %}
<div class="container">
  <h2>Lista de Despesas</h2><br>
  <table id="table_despesaslista" class="table table-hover  table-bordered" >
    <caption>Despesas</caption>
    <thead class="table-dark">
      <tr>
        <th scope="col" width="10%">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Tipo</th>
        <th scope="col">Valor ( € )</th>
        <th scope="col" width="10%">Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for despesa_atual in despesa_lista %}
    <!-- Class "clicable-row" permite nos que ao clicar na linha da tabela nos leve para onde desejamos -->
    <tr class='clickable-row' data-href= "{{ despesa_atual.get_detalhes_url }}">
      <th>{{ despesa_atual.id }}</th>
      <td>{{ despesa_atual.nome }}</td>
      <td>{{ despesa_atual.tipo_despesa }}</td>
      <td>{{ despesa_atual.valor }}</td>
      <td>
        <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{{ despesa_atual.get_atualiza_url }}" class="btn btn-secondary">{% bs_icon 'pencil-square' %}</a>
        <a href="{{ despesa_atual.get_elimina_url }}" class="btn btn-danger">{% bs_icon 'trash3' %}</a>
      </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<!-- Script DataTables Sort -->
<script>
    $(document).ready(function() {
      $('#table_despesaslista').DataTable({
          dom: 'Blfrtip',
          lengthMenu: [
              [10, 25, 50, -1],
              ['10', '25', '50', 'All']
          ],
          buttons: [
            {
                extend: 'collection',
                text: 'Export',
                buttons: ['csvHtml5', 'pdfHtml5']
            }
          ]
      });
    } );
</script>

<!-- Script JQuery Clickable Row -->
<script>
    jQuery(document).ready(function($) {
       $(document).off('click','.clickable-row').on('click','.clickable-row',function() {
          window.document.location = $(this).data("href");
       });
    });
</script>
{% endblock %}

financial_control/templates/despesa/despesa_lista_sucesso.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-success border border-dark" role="alert">
    <h5>Operação realizada com sucesso!</h5>
</div>
<div class="container">
  <h2>Lista de Despesas</h2><br>
  <table id="table_despesaslista" class="table table-hover  table-bordered" >
    <caption>Despesas</caption>
    <thead class="table-dark">
      <tr>
        <th scope="col" width="10%">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Tipo</th>
        <th scope="col">Valor ( € )</th>
        <th scope="col" width="10%">Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for despesa_atual in despesa_lista %}
    <!-- Class "clicable-row" permite nos que ao clicar na linha da tabela nos leve para onde desejamos -->
    <tr class='clickable-row' data-href= "{{ despesa_atual.get_detalhes_url }}">
      <th>{{ despesa_atual.id }}</th>
      <td>{{ despesa_atual.nome }}</td>
      <td>{{ despesa_atual.tipo_despesa }}</td>
      <td>{{ despesa_atual.valor }}</td>
      <td>
        <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{{ despesa_atual.get_atualiza_url }}" class="btn btn-secondary">Editar</a>
        <a href="{{ despesa_atual.get_elimina_url }}" class="btn btn-danger">Eliminar</a>
      </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<!-- Script DataTables Sort -->
<script>
    $(document).ready(function() {
      $('#table_despesaslista').DataTable({
          dom: 'Blfrtip',
          lengthMenu: [
              [10, 25, 50, -1],
              ['10', '25', '50', 'All']
          ],
          buttons: [
            {
                extend: 'collection',
                text: 'Export',
                buttons: ['csvHtml5', 'pdfHtml5']
            }
          ]
      });
    } );
</script>

<!-- Script JQuery Clickable Row -->
<script>
    jQuery(document).ready(function($) {
       $(document).off('click','.clickable-row').on('click','.clickable-row',function() {
          window.document.location = $(this).data("href");
       });
    });
</script>
{% endblock %}

financial_control/templates/despesa/despesa_registo.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container w-75 p-3 rounded bg-light border border-dark">
    <h1>Registar Despesa</h1>
    <p>Nesta área pode registar uma despesa.</p><br>
    <form method="POST">
      {% csrf_token %}
      <div class="row mb-3">
        <label class="col col-form-label">Nome</label>
        <div class="col-sm-10">
          {{ form.nome }}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Descrição</label>
        <div class="col-sm-10">
          {{ form.descricao }}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Valor ( € )</label>
        <div class="col-sm-10">
          {{ form.valor|as_crispy_field }}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Tipo</label>
        <div class="col-sm-10">
          {{ form.tipo_despesa }}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Data</label>
        <div class="col-sm-10">
          {{ form.date|as_crispy_field }}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Registar</button>
    </form>
</div>
<!-- DatePicker Script-->
<script>
    $(document).ready(function() {
      $('#id_date').datepicker({dateFormat: "yy-mm-dd"});
    });
</script>
{% endblock %}

financial_control/templates/despesa/despesa_registo_invalido.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="alert alert-warning border border-dark" role="alert">
      <h3><strong>WARNING:</strong> Ainda não criou nenhum tipo de despesa para associar à sua despesa!</h3>
      <h4>Por favor, primeiro crie um tipo de despesa!</h4>
    </div>
</div>
{% endblock %}

financial_control/templates/despesa/despesa_visaogeral.html
{% extends 'base.html' %}

{% load bootstrap_icons %}

{% block content %}

<!-- Small Box (Stat card) -->
<h5 class="mb-2 mt-4"></h5>
<h1 style="text-align:center;"> Visão Geral Sobre as Despesas</h1><br><br>
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>{{despesas_7dias_total}}€ </h3>
        <p>Ultimos 7 Dias</p>
      </div>
        <div class="icon">
           {% bs_icon 'currency-euro' size='1em' %}
          </div>
        <div class="small-box bg-yellow">
          <a href="{% url 'despesa-7dias-lista-view' %}" class="small-box-footer">
            Ver Despesas {% bs_icon 'arrow-right-square' %}
          </a>
        </div>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box bg-success">

      <div class="inner">
        <h3>{{despesas_30dias_total}}€ </h3>
        <p>Ultimos 30 Dias</p>
      </div>
        <div class="icon">
           {% bs_icon 'currency-euro' size='1em' %}
          </div>
        <div class="small-box bg-yellow">
          <a href="{% url 'despesa-30dias-lista-view' %}" class="small-box-footer">
            Ver Despesas {% bs_icon 'arrow-right-square' %}
          </a>
        </div>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box bg-orange">
      <div class="inner">
        <h3 style="color:white;">{{despesas_6meses_total}}€ </h3>
        <p style="color:white;">Ultimos 6 Meses</p>
      </div>
        <div class="icon">
           {% bs_icon 'currency-euro' size='1em' %}
          </div>
        <div class="small-box bg-yellow">
          <a href="{% url 'despesa-6meses-lista-view' %}" class="small-box-footer">
            Ver Despesas {% bs_icon 'arrow-right-square' %}
          </a>
        </div>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small card -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>{{despesas_1ano_total}}€ </h3>
        <p>Ultimo Ano</p>
      </div>
        <div class="icon">
           {% bs_icon 'currency-euro' size='1em' %}
          </div>
        <div class="small-box bg-yellow">
          <a href="{% url 'despesa-1ano-lista-view' %}" class="small-box-footer">
            Ver Despesas {% bs_icon 'arrow-right-square' %}
          </a>
        </div>
    </div>
  </div>
</div>
<script>
    var ctx = document.getElementById('despesas_chart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: ["Despesas"],
            datasets: [{
                data: [{{ total_custos }}],
                backgroundColor: [
                    'rgba(245, 79, 32, 0.8)',
                ],
                borderColor: [
                    'rgba(0, 0, 0, 1)',
                ],
                borderWidth: 2
            }]
        },
        options: {
            scales: {

            }
        }
    });
</script>
{% endblock %}

financial_control/templates/despesa/despesa_visaogeral_1ano.html
{% extends 'base.html' %}
{% load bootstrap_icons %}
{% block content %}
<div class="container">
  <h2>Despesas - Ultimo Ano</h2><br>
  <table id="table_despesaslista" class="table table-hover  table-bordered" >
    <caption>Despesas</caption>
    <thead class="table-dark">
      <tr>
        <th scope="col" width="10%">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Tipo</th>
        <th scope="col">Valor ( € )</th>
        <th scope="col">Data</th>
        <th scope="col" width="10%">Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for despesa_atual in despesas_1ano_lista %}
    <!-- Class "clicable-row" permite nos que ao clicar na linha da tabela nos leve para onde desejamos -->
    <tr class='clickable-row' data-href= "{{ despesa_atual.get_detalhes_url }}">
      <th>{{ despesa_atual.id }}</th>
      <td>{{ despesa_atual.nome }}</td>
      <td>{{ despesa_atual.tipo_despesa }}</td>
      <td>{{ despesa_atual.valor }}</td>
      <td>{{ despesa_atual.date }}</td>
      <td>
        <div class="btn-group" role="group" aria-label="Basic example">
        <a href="{{ despesa_atual.get_atualiza_url }}" class="btn btn-secondary">{% bs_icon 'pencil-square' %}</a>
        <a href="{{ despesa_atual.get_elimina_url }}" class="btn btn-danger">{% bs_icon 'trash3' %}</a>
      </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<!-- Script DataTables Sort -->
<script>
    $(document).ready(function() {
      $('#table_despesaslista').DataTable({
          dom: 'Blfrtip',
          lengthMenu: [
              [10, 25, 50, -1],
              ['10', '25', '50', 'All']
          ],
          buttons: [
            {
                extend: 'collection',
                text: 'Export',
                buttons: ['csvHtml5', 'pdfHtml5']
            }
          ]
      });
    } );
</script>

<!-- Script JQuery Clickable Row -->
<script>
    jQuery(document).ready(function($) {
       $(document).off('click','.clickable-row').on('click','.clickable-row',function() {
          window.document.location = $(this).data("href");
       });
    });
</script>
{% endblock %}

financial_control/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>HOME PAGE DE TESTE!</h1>
{% endblock %}

financial_control/templates/tipodespesa/tipodespesa_atualiza.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container w-75 p-3 rounded bg-light border border-dark">
    <h1>Atualizar Tipo -  <span style="color:blue;">{{ tipodespesa.nome}}</span></h1>
    <p>Nesta área pode editar/atualizar as informações acerca do tipo de despesa.</p><br>
    <form method="POST">
      {% csrf_token %}
      <div class="row mb-3">
        <label class="col col-form-label">Nome</label>
        <div class="col-sm-10">
          {{ form.nome}}
        </div>
      </div>
      <div class="row mb-3">
        <label class="col col-form-label">Descrição</label>
        <div class="col-sm-10">
          {{ form.descricao}}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>
{% endblock %}